name: track
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.9.0=py37hc8dfbb8_1
  - astroid=2.4.2=py37_0
  - attrs=19.3.0=py_0
  - autopep8=1.5.3=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h18b612c_1001
  - coloredlogs=14.0=py37hc8dfbb8_1
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=he4413a7_1000
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.10.2=h5ab3b9f_0
  - future=0.18.2=py37hc8dfbb8_1
  - glib=2.63.1=h3eb4bd4_1
  - graphite2=1.3.13=he1b5a44_1001
  - grpcio=1.30.0=py37hb0870dc_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hc401514_3
  - humanfriendly=8.2=py37_0
  - icu=58.2=hf484d3e_1000
  - imageio=2.8.0=py_0
  - importlib-metadata=1.7.0=py37hc8dfbb8_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=217
  - ipydatawidgets=4.0.1=py_0
  - ipykernel=5.3.0=py37h5ca1d4c_0
  - ipyscales=0.5.0=pyh9f0ad1d_0
  - ipython=7.15.0=py37hc8dfbb8_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.17.1=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.15.1=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - k3d=2.8.2=pyh9f0ad1d_0
  - kiwisolver=1.2.0=py37h99015e2_0
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=he1b5a44_1001
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.3=h8b12597_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h14c3975_1000
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_0
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37hef1b27d_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h8f50634_1001
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - more-itertools=8.4.0=py_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.6=py_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=6.0.3=py37hc8dfbb8_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1g=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.0.5=py37h0573a6f_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.13.1=py37hc8dfbb8_2
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.9.0=pyh9f0ad1d_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycodestyle=2.6.0=py_0
  - pygments=2.6.1=py_0
  - pylint=2.5.3=py37_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pyrsistent=0.16.0=py37h8f50634_0
  - pytest=5.4.3=py37hc8dfbb8_0
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37h7b6447c_0
  - pyzmq=19.0.1=py37hac76be4_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.23.1=py37h423224d_0
  - scipy=1.4.1=py37h0b6359f_0
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - send2trash=1.5.0=py_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.32.2=h62c20be_0
  - statsmodels=0.11.1=py37h8f50634_2
  - tensorboard=1.15.0=py37_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - torchvision=0.5.0=py37_cu100
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.46.1=pyh9f0ad1d_0
  - traitlets=4.3.3=py37hc8dfbb8_1
  - traittypes=0.2.1=py_1
  - trimesh=3.7.7=pyh9f0ad1d_0
  - typed-ast=1.4.1=py37h7b6447c_0
  - wcwidth=0.2.4=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yagmail=0.11.224=py_0
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - ase==3.19.1
    - bottle==0.12.18
    - bottle-websocket==0.2.9
    - cachetools==4.1.1
    - certifi==2020.6.20
    - chardet==3.0.4
    - click==7.1.2
    - cupy-cuda102==7.6.0
    - cython==0.29.20
    - eel==0.13.0
    - fastrlock==0.5
    - filelock==3.0.12
    - flowiz==2.3.1
    - freetype-py==2.1.0.post1
    - gevent==20.6.2
    - gevent-websocket==0.10.1
    - glfw==1.11.2
    - glumpy==1.1.0
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - googledrivedownloader==0.4
    - greenlet==0.4.16
    - h5py==2.10.0
    - hydra-core==0.11.3
    - idna==2.10
    - isodate==0.6.0
    - kornia==0.3.1
    - llvmlite==0.33.0
    - lmdb==0.98
    - mock==4.0.2
    - msgpack==1.0.0
    - msgpack-numpy==0.4.6.post0
    - networkx==2.4
    - nose==1.3.7
    - numba==0.50.1
    - numpy==1.19.0
    - oauthlib==3.1.0
    - omegaconf==1.4.1
    - plyfile==0.6
    - pointnet2-ops==3.0.0
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.7
    - pyopengl==3.1.0
    - pyrender==0.1.43
    - python-pcl==0.3.0rc1
    - pytorch-lightning==0.8.1
    - rdflib==5.0.0
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - setuptools==49.1.0
    - tensorboard-plugin-wit==1.7.0
    - tensorboardx==2.1
    - torch==1.5.0
    - torch-cluster==1.5.6
    - torch-geometric==1.6.0
    - torch-scatter==2.0.4
    - torch-sparse==0.6.1
    - torch-spline-conv==1.2.0
    - torchgeometry==0.1.2
    - triangle==20200424
    - urllib3==1.25.9
    - wheel==0.34.2
    - whichcraft==0.6.1
    - zope-event==4.4
    - zope-interface==5.1.0
prefix: /home/jonfrey/miniconda3/envs/track

